### ISSUE TITLE
Hello, I have the same problem. Even my HomePilot 1 does not offer the possibility to enter a password. Is there a version of the integration that doesn't require a password?

### ISSUE THREAD

**Issue by flkontakt** [peribeir/homeassistant-rademacher#117]
Hello, I have the same problem. Even my HomePilot 1 does not offer the possibility to enter a password. Is there a version of the integration that doesn't require a password?
![02](https://github.com/peribeir/homeassistant-rademacher/assets/77227687/cde53d25-54f0-4cf0-ab1a-8b5c28c07f2f)
![01](https://github.com/peribeir/homeassistant-rademacher/assets/77227687/69b3ea6e-82e2-4c49-81eb-b288c5e66188)

_Originally posted by @flkontakt in https://github.com/peribeir/homeassistant-rademacher/issues/2#issuecomment-2067944270_

**Comment by peribeir** [comment]
Hi,
As @BAERnado mentioned in his comment, your hardware uses a completely different API than the one used in this integration.
I don't even know where to get started in order to support it. I would need to have the device to be able to do any work.
You say you use ioBroker currently, I see there is an addon to integrate ioBroker in HA. Maybe you can use it.
https://github.com/ioBroker/ioBroker.hass
Hope this helps.

**Comment by peribeir** [comment]
Closing as this is not an issue, Integration is not compatible with this API
