### ISSUE TITLE
Motion sensor 9484

### ISSUE THREAD

**Issue by thmnxo4** [peribeir/homeassistant-rademacher#21]
Hi Pedro,

I will use Rademacher motion sensors 9484 soon.

Interested in integrate that device? :-)

Regards

**Comment by peribeir** [comment]
Hi

Sure, it's always good to add some more devices to the list.
I also recently added Contact Sensor, which should be similar.

When you have the sensor installed and working with the hub, just reply back and we can work together to add it to the integration code.

Best Regards,
Pedro

**Comment by thmnxo4** [comment]
Great. It will take a little while but I will inform as soon as the sensors
are running.

Pedro Ribeiro ***@***.***> schrieb am Mo., 7. Feb. 2022,
22:20:

**Comment by thmnxo4** [comment]
Hi,
Just want to  inform that I will not buy this sensor.

I now use zigbee2mqtt for different sensors. Cheaper and more flexible ;-)

**Comment by peribeir** [comment]
I guess I'll close this for now, and if someone else gets one of these sensors, then I'll try to integrate them.

**Comment by Kraetzik** [comment]
Hi I Just started using HA from ei23.de Script.
I already installed Hacs with Radermacher Bridge and I started top use entities from my Homepilot with HA.
Currently there are Motion Sensors integrated as binary Sensors. Since I am using These Sensors to Control the lighting in the Gallery I am switching these Sensors between Manual and Automatic Mode during day and night shifting. During Manual Mode the Homepilot can observe Motion detection but the HA Bridge does Not. I would Like to use These Motion Sensors for an alarm Automation in HA. Without a possibility to Switch These Motion Sensors to automatic, Home Assistent will Not recognize a detection and will Not start the Alarm Automation.
Ist there any Chance to integrate the Switch in the device for Automatic and Manual Mode?
I could supply the device Code from homepilot If necessary. I also have other Radermacher devices If requested.
Thanks for your Work. I really Love it!

**Comment by DonDisco-TheBest** [comment]
Hello there,

I am using a couple of Rademacher products (thermostates, shutter actuators and motion sensors) and started using HA just a couple of weeks ago. Actually I moved over from the io broker. 
Everything seems to work just fine with the Rademacher integragtion but I am having an issue with a huge delay of the motion sensors state in HA. The sensors are integrated as binary sensors and after the sensors detect motion physically (indicated by a red light at the sensor itself) it takes between 10 to 20 seconds before the state switches in HA. I know from experience with the io broker that the sensors are capable of transmitting the state-change without delay. As the motion sensors are not included in the list of supported devices and this issue does not seem to be followed up, I am wondering if that has to do with the way these sensors are (not) integrated. Getting rid of the delay would really be the icing on the cake of this fantastic integration.

Thanks for your support
