### ISSUE TITLE
DuoFern Aktor 9471-1 possible to get opening and closing state?

### ISSUE THREAD

**Issue by Soulfly999** [peribeir/homeassistant-rademacher#76]
Hey, i don't know if it's an issue with the integration or the actor? Is it possible to get an 'opening' or 'closing' state if the cover runs.

In my test the cover state changed only from open to close in 2 sek. while the cover is still running.

**Comment by peribeir** [comment]
Hi

Unfortunately, I didn't find any way to get the opening/closing status from the data provided by the homepilot bridge.
I have the Rollotron Shutters and I have the same issue. So the only info I get get is what you see in the state.

I will close this issue because it is not possible to get such states.

Thank you for using my integration, I hope it helps you automate Homepilot devices with Home Assistant.
